version: '3.8'

services:
  app:
    container_name: whatsapp_web_api
    image: chrishubert/whatsapp-web-api:latest # Pull the image from Docker Hub
    # restart: always
    ports:
      - "3000:3000"
    environment:
      # - API_KEY=your_global_api_key_here  # OPTIONAL
      - BASE_WEBHOOK_URL=https://sendgo-api.vercel.app/webhook
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
      - SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      # ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - DISABLED_CALLBACKS=message_ack  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder